service: auth-server

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  timeout: 60

functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: true
  refreshAccessToken :
    handler: handler.refreshAccessToken
    events:
      - http:
          path: api/refresh/{code}
          method: get
          cors: true